### ISSUE TITLE
Template is unlicensed 

### ISSUE THREAD

**Issue by ioridev** [as1605/opencv_flutter_ffi#4]
Please add the appropriate license for ease of use as a template.

From the [GitHub guidance on licensing](https://help.github.com/en/articles/licensing-a-repository):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

**Comment by as1605** [comment]
Thanks for the issue! I have added MIT License now
