### ISSUE TITLE
Do you plan to support the latest Flutter?

### ISSUE THREAD

**Issue by Yuya-Tominaga** [as1605/opencv_flutter_ffi#5]
I am Japanese, so I think my English is poor. Sorry.

I am very grateful for this package.
There are very few OpenCV packages that support the Web, and this package is very useful.
Do you have any plans to support the latest Flutter versions and their associated dependency packages in the future?

If not, do you have plans for someone else to take over maintenance?

**Comment by Yuya-Tominaga** [comment]
I'm sorry if I came across as rude.

**Comment by as1605** [comment]
Hi, thanks for exploring this package.

Yes we can try to support latest Flutter versions too! 
Let me know if you want to contribute for maintenance.

**Comment by ioridev** [comment]
@Yuya-Tominaga 
Created PR for updates to build with latest Flutter.
https://github.com/as1605/opencv_flutter_ffi/pull/6

**Comment by as1605** [comment]
Thanks @ioridev , I have merged your PR 😄

**Comment by Yuya-Tominaga** [comment]
@ioridev @as1605 Thank you for taking the time to do this.
We both thank you from the bottom of our hearts.
This issue is closed as it has been resolved.

I'll be back somewhere else.
